// Package rule は Decision パターンの規約本文を埋め込んで配布する。
//
// 本文をこのモジュールに持たせることで、ツールの版と規約の版が go.mod で一緒に
// 固定される。取り込む側は書き出して commit するだけでよく、どの版に従っているかが
// 履歴に残る。
package rule

import (
	_ "embed"
	"strings"
)

//go:embed decision-pattern.md
var body string

// generatedNotice は書き出したファイルを手で直させないための注記。
// frontmatter の後に置く。先頭に置くと frontmatter として読まれない。
const generatedNotice = "<!-- Generated by decision-pattern. DO NOT EDIT. 変更は github.com/tomoemon/go-decision-pattern へ -->\n\n"

// Render は規約の本文を返す。paths を渡すと frontmatter を付ける。
//
// paths は取り込む側のディレクトリ構成で決まるので本文には持たせない。
// 空で書き出すとリポジトリ全体向けの指示として扱われ、Decision と無関係な作業でも
// 読み込まれる。
func Render(paths []string) string {
	var b strings.Builder
	if len(paths) > 0 {
		b.WriteString("---\npaths:\n")
		for _, p := range paths {
			b.WriteString(`  - "` + p + "\"\n")
		}
		b.WriteString("---\n\n")
	}
	b.WriteString(generatedNotice)
	b.WriteString(body)
	return b.String()
}
