// Package rule は Decision パターンの規約本文を埋め込んで配布する。
//
// 本文をこのモジュールに持たせることで、ツールの版と規約の版が go.mod で一緒に
// 固定される。取り込む側は書き出して commit するだけでよく、どの版に従っているかが
// 履歴に残る。
package rule

import (
	_ "embed"
	"regexp"
	"strings"
)

//go:embed decision-pattern.md
var body string

// versionLine は本文の先頭付近に置いた版の行を拾う。
// 版を本文に持たせるのは、ツールを入れずにコピーだけで取り込んだ利用者が、
// 手元の写しと配布元を突き合わせられるようにするため。go.mod に載らない
// 取り込み方では、版を知る手段がここしかない。
var versionLine = regexp.MustCompile(`(?m)^規約バージョン: (v[0-9]+\.[0-9]+\.[0-9]+)`)

// Version は規約本文が宣言している版を返す。
func Version() string {
	m := versionLine.FindStringSubmatch(body)
	if m == nil {
		return ""
	}
	return m[1]
}

// generatedNotice は書き出したファイルを手で直させないための注記。
// frontmatter の後に置く。先頭に置くと frontmatter として読まれない。
const generatedNotice = "<!-- Generated by decision-pattern. DO NOT EDIT. 変更は github.com/tomoemon/go-decision-pattern へ -->\n\n"

// Render は規約の本文を返す。paths を渡すと frontmatter を付ける。
//
// paths は取り込む側のディレクトリ構成で決まるので本文には持たせない。
// 空で書き出すとリポジトリ全体向けの指示として扱われ、Decision と無関係な作業でも
// 読み込まれる。
func Render(paths []string) string {
	var b strings.Builder
	if len(paths) > 0 {
		b.WriteString("---\npaths:\n")
		for _, p := range paths {
			b.WriteString(`  - "` + p + "\"\n")
		}
		b.WriteString("---\n\n")
	}
	b.WriteString(generatedNotice)
	b.WriteString(body)
	return b.String()
}
