package flow

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// generatedHeader は生成物であることを示す。手で直すと次の生成で消える。
const generatedHeader = "<!-- Code generated by decision-pattern. DO NOT EDIT. -->\n\n"

// WriteStdout は全 Decision を 1 つの Markdown として書く。
func WriteStdout(w io.Writer, decisions []*Decision) {
	fmt.Fprintln(w, "# Decision フロー")
	fmt.Fprintln(w)
	for _, d := range decisions {
		fmt.Fprintln(w, Render(d))
	}
}

// WriteFiles は Decision ごとに 1 ファイル書く。1 ファイルにまとめると、
// 1 つの Decision を直しただけで全体の差分が動いてレビューしづらくなる。
func WriteFiles(outDir string, decisions []*Decision, log io.Writer) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}
	for _, d := range decisions {
		name := filepath.Base(d.Package) + "." + d.Name + ".md"
		path := filepath.Join(outDir, name)
		if err := os.WriteFile(path, []byte(generatedHeader+Render(d)), 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", path, err)
		}
		fmt.Fprintln(log, "wrote", path)
	}
	return nil
}

// ReportWarnings は警告を書き出し、1 件でもあったかを返す。
func ReportWarnings(w io.Writer, decisions []*Decision) bool {
	warned := false
	for _, d := range decisions {
		for _, msg := range d.Warnings {
			warned = true
			fmt.Fprintf(w, "warning: %s.%s: %s\n", d.Package, d.Name, msg)
		}
	}
	return warned
}
