package flow

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
)

// generatedHeader は生成物であることを示す。手で直すと次の生成で消える。
const generatedHeader = "<!-- Code generated by decision-pattern. DO NOT EDIT. -->\n\n"

// Renderer は Decision 1 つ分を Markdown にする。形式ごとの違いはこの関数だけ。
type Renderer func(*Decision) string

// -shape で選べる描き方の名前。
const (
	ShapeDecision = "decision" // 判断もノードにする
	ShapeState    = "state"    // 状態だけをノードにする。判断は辺のラベルになる

	// DefaultShape は -shape を省いたときの描き方。選んだ理由は
	// internal/flow/README.md の「図の形」を参照。
	DefaultShape = ShapeDecision
)

// Renderers は名前から描き方を引く。
var Renderers = map[string]Renderer{
	ShapeDecision: RenderDecisionShape,
	ShapeState:    Render,
}

// RendererNames は Renderers のキーを並び順を固定して返す。
func RendererNames() []string {
	names := make([]string, 0, len(Renderers))
	for k := range Renderers {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

// WriteStdout は全 Decision を 1 つの Markdown として書く。
func WriteStdout(w io.Writer, decisions []*Decision, render Renderer) {
	fmt.Fprintln(w, "# Decision フロー")
	fmt.Fprintln(w)
	for _, d := range decisions {
		fmt.Fprintln(w, render(d))
	}
}

// WriteFiles は Decision ごとに 1 ファイル書く。1 ファイルにまとめると、
// 1 つの Decision を直しただけで全体の差分が動いてレビューしづらくなる。
func WriteFiles(outDir string, decisions []*Decision, render Renderer, log io.Writer) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}
	for _, d := range decisions {
		name := filepath.Base(d.Package) + "." + d.Name + ".md"
		path := filepath.Join(outDir, name)
		if err := os.WriteFile(path, []byte(generatedHeader+render(d)), 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", path, err)
		}
		fmt.Fprintln(log, "wrote", path)
	}
	return nil
}

// ReportWarnings は警告を書き出し、1 件でもあったかを返す。
func ReportWarnings(w io.Writer, decisions []*Decision) bool {
	warned := false
	for _, d := range decisions {
		for _, msg := range d.Warnings {
			warned = true
			fmt.Fprintf(w, "warning: %s.%s: %s\n", d.Package, d.Name, msg)
		}
	}
	return warned
}
